// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DejaVu.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20231120202745_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1.Models.Employee", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<DateTime>("BirthDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Image")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Position")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Surname")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Employees");

                b.HasData(
                    new
                    {
                        Id = 1,
                        BirthDate = new DateTime(1992, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Image = "/images/Martin.jpg",
                        Name = "Martin",
                        Position = "Marketing Expert",
                        Surname = "Simpson"
                    },
                    new
                    {
                        Id = 2,
                        BirthDate = new DateTime(1995, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Image = "/images/Jacob.jpg",
                        Name = "Jacob",
                        Position = "Manager",
                        Surname = "Hawk"
                    },
                    new
                    {
                        Id = 3,
                        BirthDate = new DateTime(2000, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Image = "/images/Elizabeth.jpg",
                        Name = "Elizabeth",
                        Position = "Software Engineer",
                        Surname = "Geil"
                    },
                    new
                    {
                        Id = 4,
                        BirthDate = new DateTime(1997, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Image = "/images/Kate.jpg",
                        Name = "Kate",
                        Position = "Admin",
                        Surname = "Metain"
                    },
                    new
                    {
                        Id = 5,
                        BirthDate = new DateTime(1990, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Image = "/images/Michael.jpg",
                        Name = "Michael",
                        Position = "Marketing Expert",
                        Surname = "Cook"
                    },
                    new
                    {
                        Id = 6,
                        BirthDate = new DateTime(2001, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Image = "/images/John.jpg",
                        Name = "John",
                        Position = "Software Engineer",
                        Surname = "Snow"
                    },
                    new
                    {
                        Id = 7,
                        BirthDate = new DateTime(1999, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Image = "/images/Nina.jpg",
                        Name = "Nina",
                        Position = "Software Engineer",
                        Surname = "Soprano"
                    },
                    new
                    {
                        Id = 8,
                        BirthDate = new DateTime(2000, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                        Image = "/images/Tina.jpg",
                        Name = "Tina",
                        Position = "Team Leader",
                        Surname = "Fins"
                    });
            });
#pragma warning restore 612, 618
        }
    }
}
